import MoleculeFooter from "@/components/molecules/m_footer";
import MoleculesNavbar from "@/components/molecules/m_navbar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode;}>) {
  const menuItem = [
    { title: "Home", target: "/" },
    { title: "About", target: "#aboutSection" },
    { title: "Treatment", target: "#treatmentSection" },
    { title: "After Care", target: "/after_care" },
    { title: "News", target: "/news" },
    { title: "Promo", target: "#promoSection" },
    { title: "Testimonial", target: "#testimonialSection" },
    { title: "Contact", target: "#contactSection" }
  ]

  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppins.className} antialiased`}>
        <MoleculesNavbar menuItem={menuItem}/>
        <div className="min-h-[90vh]">
          {children}
        </div>
        <MoleculeFooter/>
      </body>
    </html>
  );
}
